name: building-blocks

on: push

jobs:
  echo-hello: 
    runs-on: ubuntu-latest
    steps:
        - name: Say Hello
          run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
        - name: Successful step
          run: |
<<<<<<< HEAD
            echo "This step will succeed"
=======
            echo "This step will success"
>>>>>>> 4f312b9659286dffa660d6ec7e00d126ac63db66
            exit 0
        - name: say Goodbye
          run: echo "Goodbye!"
